OpenSSL -> OpenTLS

diff --git a/util/openssl-format-source b/util/openssl-format-source
--- a/util/openssl-format-source
+++ b/util/openssl-format-source
@@ -1,18 +1,18 @@
 #!/bin/sh
 #
-# Copyright 2015-2016 The OpenSSL Project Authors. All Rights Reserved.
+# Copyright 2015-2016 The Opentls Project Authors. All Rights Reserved.
 #
 # Licensed under the Apache License 2.0 (the "License").  You may not use
 # this file except in compliance with the License.  You can obtain a copy
 # in the file LICENSE in the source distribution or at
-# https://www.openssl.org/source/license.html
+# https://www.opentls.org/source/license.html
 
 #
-# openssl-format-source
-# - format source tree according to OpenSSL coding style using indent
+# opentls-format-source
+# - format source tree according to Opentls coding style using indent
 #
 # usage:
-#   openssl-format-source [-v] [-n] [file|directory] ...
+#   opentls-format-source [-v] [-n] [file|directory] ...
 #
 # note: the indent options assume GNU indent v2.2.10 which was released
 #       Feb-2009 so if you have an older indent the options may not
@@ -44,12 +44,12 @@ COMMENTS=false
 CHANGED=false
 DEBUG=""
 
-# for this exercise, we want to force the openssl style, so we roll
+# for this exercise, we want to force the opentls style, so we roll
 # our own indent profile, which is at a well known location
 INDENT_PROFILE="$HERE/indent.pro"
 export INDENT_PROFILE
 if [ ! -f "$INDENT_PROFILE" ]; then
-  echo "$0: unable to locate the openssl indent.pro file" >&2
+  echo "$0: unable to locate the opentls indent.pro file" >&2
   exit 1
 fi
 
