fixup! Fix make check-format target

diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -1180,8 +1180,18 @@ lint: ## Evaluate C code via "splint"
            echo splint -DLINT -posixlib -preproc -D__gnuc_va_list=void \
 	   -I. -Iinclude -Iapps/include $(CRYPTOHEADERS) $(SSLHEADERS) $(SRCS) )
 
-.PHONY: check-format
-check-format: ## Evaluate C code according to OpenSSL coding standards
+CLANG_FORMAT_DIFF := clang-format-diff
+DIFFCMD := $(shell command -v ${CLANG_FORMAT_DIFF})
+
+.PHONY: check-format check-clang-format-diff-cmd
+check-clang-format-diff-cmd:
+	@if [ -z "${DIFFCMD}" ]; then \
+		echo "Unable to find ${CLANG_FORMAT_DIFF}";\
+		echo "Please set the CLANG_FORMAT_DIFF variable to your clang-format-diff command";\
+		exit 1;\
+	fi
+
+check-format: check-clang-format-diff-cmd ## Evaluate C code according to OpenSSL coding standards
 	( cd $(SRCDIR); git diff -U0 --no-prefix --no-color | clang-format-diff )
 
 generate_apps:
